### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Crease29** [trmcnvn/chrome-addon#1]
Hi,

I'd really like to use your action in one of my projects, but I'm not sure how to get the client id, client secret and refresh token.
I tried to follow [this documentation from Google](https://developer.chrome.com/webstore/using_webstore_api) but also didn't get the keys I needed.

Would be super nice, if you can write a quick documentation with links about how to retrieve the needed credentials.

Thanks!

**EDIT:** Here I found a very good documentation! https://github.com/DrewML/chrome-webstore-upload/blob/master/How%20to%20generate%20Google%20API%20keys.md

**Comment by trmcnvn** [comment]
Thanks for the link! I've included it in the README.
