### ISSUE TITLE
Task failed with no output

### ISSUE THREAD

**Issue by Mte90** [trmcnvn/chrome-addon#14]
As you can see on https://github.com/Mte90/GlotDict/runs/1510260792?check_suite_focus=true the firefox one worked but the Chrome one no and there is no output to understand what failed.

**Comment by trmcnvn** [comment]
It seems to be that it's telling you exactly what failed. You supplied an incorrect options key.

```
Warning: Unexpected input(s) 'file-name', valid inputs are ['extension', 'zip', 'client-id', 'client-secret', 'refresh-token']
```

**Comment by Mte90** [comment]
Sorry when I opened the ticket in the GH action there was no output, I will check that.

**Comment by Mte90** [comment]
I had again the same issue: https://github.com/Mte90/GlotDict/runs/1621923791?check_suite_focus=true

There is just a 404 error
