### ISSUE TITLE
More Comprehensive logging

### ISSUE THREAD

**Issue by deef0000dragon1** [trmcnvn/chrome-addon#4]
we are recieving an error when [attempting to run the action](https://github.com/igrigorik/videospeed/commit/98d938741d158143f3530ba7ae3dceb9cee91d4d/checks?check_suite_id=372107312) . I THINK that the issue is that I used the wrong name, (how its displayed on the store, not in the manifest), but debugging is very difficult as there is little to no logging of what is actually happening in the action.

**Comment by trmcnvn** [comment]
Yeah, you'll need to refer to the extension with its identifier and not its name.

Example:

https://chrome.google.com/webstore/detail/mute-tab/blljobffcekcbopmkgfhpcjmbfnelkfg

would be referred to as `blljobffcekcbopmkgfhpcjmbfnelkfg`

-----

The action does log its responses from the Chrome API -- You can enable debug logging on an action by following the steps [here](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#step-debug-logs)

**Comment by deef0000dragon1** [comment]
It might be relavent to add that to the readme. Thanks for the help.
